# Generated by Django 4.1.7 on 2023-03-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banaoDjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Useryash',
            new_name='patient',
        ),
    ]
